module Physics.Integrator where

import Math.Vector3
import Physics.Forces
import Physics.Types

--step one body
stepBody::R->Body->Vector3->Body --step dt with a body and acceleration vector
--this step function utilizes euler-cromer integration
stepBody dt b acc =
    let velNext = vel b ^+^ (acc ^* dt)
        posNext = pos b ^+^ (velNext ^* dt)
    in b {pos = posNext, vel = velNext}

--step entire system
stepSystem::R-> R-> R->SystemState->SystemState
stepSystem g eps dt (SystemState t bodiesList) = 
    let accList = calcAllAccel g eps bodiesList
        steppedBodies = zipWith (stepBody dt) bodiesList accList --since bodieslist and accList are the same size, we use zipWith to use stepBody for each pair of body and acceleration vector
    in SystemState(t+dt) steppedBodies

totalKE::[Body]->R --total kinetic energy
totalKE bs =
    sum [0.5 * mass b * (vel b <.> vel b) | b <- bs]

pairPE:: R-> R -> Body -> Body -> R 
pairPE g eps b1 b2
    | bodyID b1 == bodyID b2 = 0
    | otherwise = 
        let r = pos b1 ^-^ pos b2
            rSq = r<.>r
            rSoftened = sqrt(rSq + (eps * eps))
        in -(g * mass b1 * mass b2)/rSoftened

totalPE::R-> R -> [Body]-> R 
totalPE g eps bs =
    --create a tuple as a pair of bodies that generates unique pairs
    --unique pairs are generated by checking if one id is less than the other, which prevents backward duplicates
    let pairs = [(b1, b2) | b1 <- bs, b2 <- bs, bodyID b1 < bodyID b2]
    in sum [pairPE g eps b1 b2 | (b1, b2) <- pairs] --using brackets instead of parantheses since we use list comprehension

totalEnergy::R-> R -> [Body]-> R
totalEnergy g eps bs = totalKE bs + totalPE g eps bs


